### ISSUE TITLE
Проблемы в стиле кода.

### ISSUE THREAD

**Issue by GudveN** [amidovitch/PASMAN#2]
1. Нету единого стиля расставления фигурных скобок в большинстве файлов. (Примеры в файлах - logininappwindow.h , cryptographer.cpp и т.д.)
2. Убрать ненужные комментарии в header файлах после "endif" (Примеры в файлах - workwithstorage.h , mainwindow.h)
3. Убрать код из комментария в файле mainwindow.cpp
4. Нету фигурных скобок в блоке if else в файле workwithstorage.cpp

**Comment by amidovitch** [comment]
1. Расставил скобки в едином стиле.
2. Ненужные комменты убрал.
3. Убрал лишний код.
4. Добавил скобки.
